
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 11 02:45:36 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RPARENT = 46;
  public static final int LPARENT = 45;
  public static final int LTE = 36;
  public static final int CONST = 8;
  public static final int CHAR = 23;
  public static final int PERIOD = 44;
  public static final int GRT = 33;
  public static final int PRIVATE = 21;
  public static final int CONTINUE = 18;
  public static final int INTERFACE = 5;
  public static final int LST = 35;
  public static final int FOR = 15;
  public static final int SEMICOLON = 42;
  public static final int AND = 37;
  public static final int OR = 38;
  public static final int COMMA = 43;
  public static final int BOOL = 24;
  public static final int CLASS = 4;
  public static final int INC = 40;
  public static final int DIV = 29;
  public static final int NUM = 25;
  public static final int ASSIGN = 39;
  public static final int IF = 9;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 28;
  public static final int LCURLY = 49;
  public static final int ADD = 26;
  public static final int MOD = 30;
  public static final int NEQ = 32;
  public static final int BREAK = 3;
  public static final int IDENT = 22;
  public static final int VOID = 14;
  public static final int GTE = 34;
  public static final int RCURLY = 50;
  public static final int EQU = 31;
  public static final int ELSE = 7;
  public static final int PROTECTED = 20;
  public static final int LSQUARE = 47;
  public static final int ENUM = 6;
  public static final int READ = 12;
  public static final int RSQUARE = 48;
  public static final int PUBLIC = 19;
  public static final int EXTENDS = 16;
  public static final int DEC = 41;
  public static final int IMPLEMENTS = 17;
  public static final int SUB = 27;
  public static final int PRINT = 11;
}

