
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Feb 02 22:51:10 CET 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RPARENT = 43;
  public static final int LPARENT = 42;
  public static final int LTE = 33;
  public static final int CONST = 8;
  public static final int CHAR = 20;
  public static final int PERIOD = 41;
  public static final int GRT = 30;
  public static final int CONTINUE = 18;
  public static final int INTERFACE = 5;
  public static final int LST = 32;
  public static final int FOR = 15;
  public static final int SEMICOLON = 39;
  public static final int AND = 34;
  public static final int OR = 35;
  public static final int COMMA = 40;
  public static final int BOOL = 21;
  public static final int CLASS = 4;
  public static final int INC = 37;
  public static final int DIV = 26;
  public static final int NUM = 22;
  public static final int ASSIGN = 36;
  public static final int IF = 9;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 25;
  public static final int LCURLY = 46;
  public static final int ADD = 23;
  public static final int MOD = 27;
  public static final int NEQ = 29;
  public static final int BREAK = 3;
  public static final int IDENT = 19;
  public static final int VOID = 14;
  public static final int GTE = 31;
  public static final int RCURLY = 47;
  public static final int EQU = 28;
  public static final int ELSE = 7;
  public static final int LSQUARE = 44;
  public static final int ENUM = 6;
  public static final int READ = 12;
  public static final int RSQUARE = 45;
  public static final int EXTENDS = 16;
  public static final int DEC = 38;
  public static final int IMPLEMENTS = 17;
  public static final int SUB = 24;
  public static final int PRINT = 11;
}

