/* The following code was generated by JFlex 1.4.3 on 6/5/19, 12:36 AM */

package rs.ac.bg.etf.pp1;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 6/5/19, 12:36 AM from the specification file
 * <tt>spec/mjlexer.flex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYCOMMENT = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\1\1\1\1\1\3\1\0\1\1\1\2\22\0\1\4\1\45"+
    "\3\36\1\43\1\50\1\35\1\55\1\56\1\41\1\37\1\53\1\40"+
    "\1\54\1\42\12\34\1\36\1\52\1\47\1\44\1\46\2\36\32\32"+
    "\1\57\1\36\1\60\1\36\1\33\1\36\1\11\1\13\1\16\1\27"+
    "\1\14\1\24\1\10\1\32\1\21\1\32\1\15\1\17\1\12\1\22"+
    "\1\7\1\5\1\32\1\6\1\20\1\23\1\25\1\30\1\26\1\31"+
    "\2\32\1\61\1\51\1\62\1\36\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\1\13\3\1\4\1\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\1\1\13\1\14"+
    "\2\1\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\2\12\3\1\26\5\3\1\0\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\14\3\1\41\1\3\1\42\2\3\1\43\2\3"+
    "\1\44\2\3\1\45\1\46\6\3\1\47\1\50\1\3"+
    "\1\51\1\3\1\52\1\3\1\53\1\3\1\54\3\3"+
    "\1\55\4\3\1\56\1\57\3\3\1\60\3\3\1\61"+
    "\1\62";

  private static int [] zzUnpackAction() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\146\0\231\0\314\0\377\0\u0132"+
    "\0\u0165\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297\0\u02ca"+
    "\0\u02fd\0\u0330\0\u0363\0\u0396\0\146\0\u03c9\0\146\0\u03fc"+
    "\0\u042f\0\u0462\0\u0495\0\u04c8\0\u04fb\0\146\0\146\0\146"+
    "\0\146\0\146\0\146\0\146\0\146\0\146\0\u052e\0\u0561"+
    "\0\u0594\0\u05c7\0\u05fa\0\u062d\0\u0660\0\u0693\0\u06c6\0\u06f9"+
    "\0\u072c\0\u0132\0\u075f\0\u0792\0\u07c5\0\u07f8\0\u082b\0\u085e"+
    "\0\146\0\146\0\146\0\146\0\146\0\146\0\146\0\146"+
    "\0\146\0\146\0\u0891\0\u08c4\0\u08f7\0\u092a\0\u095d\0\u0990"+
    "\0\u09c3\0\u09f6\0\u0a29\0\u0a5c\0\u0a8f\0\u0ac2\0\u0132\0\u0af5"+
    "\0\u0132\0\u0b28\0\u0b5b\0\146\0\u0b8e\0\u0bc1\0\u0132\0\u0bf4"+
    "\0\u0c27\0\u0132\0\u0132\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26"+
    "\0\u0d59\0\u0132\0\u0132\0\u0d8c\0\u0132\0\u0dbf\0\u0132\0\u0df2"+
    "\0\u0132\0\u0e25\0\u0132\0\u0e58\0\u0e8b\0\u0ebe\0\u0132\0\u0ef1"+
    "\0\u0f24\0\u0f57\0\u0f8a\0\u0132\0\u0132\0\u0fbd\0\u0ff0\0\u1023"+
    "\0\u0132\0\u1056\0\u1089\0\u10bc\0\u0132\0\u0132";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\0\1\4\1\6\1\7\4\10"+
    "\1\11\1\12\1\10\1\13\2\10\1\14\1\15\1\16"+
    "\1\17\3\10\1\20\2\10\1\3\1\21\1\22\1\3"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\2\4\1\47\1\0\57\4"+
    "\66\0\1\4\64\0\1\10\1\50\26\10\14\0\1\10"+
    "\16\0\7\10\1\51\20\10\14\0\1\10\16\0\30\10"+
    "\14\0\1\10\16\0\1\10\1\52\26\10\14\0\1\10"+
    "\16\0\12\10\1\53\2\10\1\54\6\10\1\55\3\10"+
    "\14\0\1\10\16\0\2\10\1\56\7\10\1\57\15\10"+
    "\14\0\1\10\16\0\5\10\1\60\7\10\1\61\1\10"+
    "\1\62\10\10\14\0\1\10\16\0\7\10\1\63\20\10"+
    "\14\0\1\10\16\0\1\10\1\64\26\10\14\0\1\10"+
    "\16\0\2\10\1\65\1\10\1\66\23\10\14\0\1\10"+
    "\16\0\2\10\1\67\25\10\14\0\1\10\45\0\1\21"+
    "\32\0\57\70\37\0\1\71\63\0\1\72\64\0\1\73"+
    "\64\0\1\74\62\0\1\75\62\0\1\76\62\0\1\77"+
    "\66\0\1\100\63\0\1\101\14\0\1\102\64\0\2\10"+
    "\1\103\11\10\1\104\13\10\14\0\1\10\16\0\4\10"+
    "\1\105\11\10\1\106\11\10\14\0\1\10\16\0\7\10"+
    "\1\107\20\10\14\0\1\10\16\0\13\10\1\110\14\10"+
    "\14\0\1\10\16\0\20\10\1\111\7\10\14\0\1\10"+
    "\16\0\16\10\1\112\11\10\14\0\1\10\16\0\15\10"+
    "\1\113\12\10\14\0\1\10\16\0\4\10\1\114\23\10"+
    "\14\0\1\10\16\0\1\115\27\10\14\0\1\10\16\0"+
    "\16\10\1\116\11\10\14\0\1\10\16\0\21\10\1\117"+
    "\6\10\14\0\1\10\16\0\20\10\1\120\7\10\14\0"+
    "\1\10\16\0\1\10\1\121\26\10\14\0\1\10\16\0"+
    "\12\10\1\122\15\10\14\0\1\10\16\0\14\10\1\123"+
    "\13\10\14\0\1\10\46\0\1\124\32\0\3\10\1\125"+
    "\24\10\14\0\1\10\16\0\15\10\1\126\12\10\14\0"+
    "\1\10\16\0\22\10\1\127\5\10\14\0\1\10\16\0"+
    "\20\10\1\130\7\10\14\0\1\10\16\0\4\10\1\131"+
    "\23\10\14\0\1\10\16\0\7\10\1\132\20\10\14\0"+
    "\1\10\16\0\5\10\1\133\22\10\14\0\1\10\16\0"+
    "\7\10\1\134\20\10\14\0\1\10\16\0\13\10\1\135"+
    "\2\10\1\136\11\10\14\0\1\10\16\0\13\10\1\137"+
    "\14\10\14\0\1\10\16\0\12\10\1\140\15\10\14\0"+
    "\1\10\16\0\7\10\1\141\20\10\14\0\1\10\16\0"+
    "\7\10\1\142\20\10\14\0\1\10\16\0\13\10\1\120"+
    "\14\10\14\0\1\10\16\0\22\10\1\143\5\10\14\0"+
    "\1\10\16\0\1\10\1\144\26\10\14\0\1\10\16\0"+
    "\16\10\1\145\11\10\14\0\1\10\16\0\1\10\1\146"+
    "\26\10\14\0\1\10\16\0\10\10\1\147\17\10\14\0"+
    "\1\10\16\0\15\10\1\150\12\10\14\0\1\10\16\0"+
    "\16\10\1\151\11\10\14\0\1\10\16\0\14\10\1\152"+
    "\13\10\14\0\1\10\16\0\13\10\1\153\14\10\14\0"+
    "\1\10\16\0\7\10\1\154\20\10\14\0\1\10\16\0"+
    "\1\10\1\155\26\10\14\0\1\10\16\0\4\10\1\156"+
    "\23\10\14\0\1\10\16\0\15\10\1\157\12\10\14\0"+
    "\1\10\16\0\22\10\1\160\5\10\14\0\1\10\16\0"+
    "\15\10\1\161\12\10\14\0\1\10\16\0\5\10\1\162"+
    "\22\10\14\0\1\10\16\0\17\10\1\163\10\10\14\0"+
    "\1\10\16\0\5\10\1\164\22\10\14\0\1\10\16\0"+
    "\13\10\1\165\14\10\14\0\1\10\16\0\20\10\1\166"+
    "\7\10\14\0\1\10\16\0\7\10\1\167\20\10\14\0"+
    "\1\10\16\0\4\10\1\170\23\10\14\0\1\10\16\0"+
    "\7\10\1\171\20\10\14\0\1\10\16\0\15\10\1\172"+
    "\12\10\14\0\1\10\16\0\11\10\1\173\16\10\14\0"+
    "\1\10\16\0\16\10\1\174\11\10\14\0\1\10\16\0"+
    "\7\10\1\175\20\10\14\0\1\10\16\0\13\10\1\176"+
    "\14\10\14\0\1\10\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4335];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\20\1\1\11\1\1\1\11\6\1\11\11"+
    "\21\1\1\0\12\11\21\1\1\11\52\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private Symbol createSymbol(int type) {
	  return new Symbol(type, yyline + 1, yycolumn);
  }
  
  private Symbol createSymbol(int type, Object value) {
	  return new Symbol(type, yyline + 1, yycolumn, value);
  }

  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 33: 
          { return createSymbol(sym.NEW, yytext());
          }
        case 51: break;
        case 5: 
          { return createSymbol(sym.ADD, yytext());
          }
        case 52: break;
        case 6: 
          { return createSymbol(sym.SUB, yytext());
          }
        case 53: break;
        case 28: 
          { return createSymbol(sym.GTE, yytext());
          }
        case 54: break;
        case 40: 
          { return createSymbol(sym.VOID, yytext());
          }
        case 55: break;
        case 11: 
          { return createSymbol(sym.GRT, yytext());
          }
        case 56: break;
        case 29: 
          { return createSymbol(sym.LTE, yytext());
          }
        case 57: break;
        case 8: 
          { return createSymbol(sym.DIV, yytext());
          }
        case 58: break;
        case 41: 
          { return createSymbol(sym.PRINT, yytext());
          }
        case 59: break;
        case 44: 
          { return createSymbol(sym.CLASS, yytext());
          }
        case 60: break;
        case 16: 
          { return createSymbol(sym.LPARENT, yytext());
          }
        case 61: break;
        case 21: 
          { return createSymbol(sym.RCURLY, yytext());
          }
        case 62: break;
        case 38: 
          { return createSymbol(sym.ENUM, yytext());
          }
        case 63: break;
        case 4: 
          { return createSymbol(sym.NUM, new Integer(yytext()));
          }
        case 64: break;
        case 45: 
          { return createSymbol(sym.RETURN, yytext());
          }
        case 65: break;
        case 30: 
          { return createSymbol(sym.AND, yytext());
          }
        case 66: break;
        case 36: 
          { return createSymbol(sym.READ, yytext());
          }
        case 67: break;
        case 7: 
          { return createSymbol(sym.MUL, yytext());
          }
        case 68: break;
        case 9: 
          { return createSymbol(sym.MOD, yytext());
          }
        case 69: break;
        case 32: 
          { yybegin(YYINITIAL);
          }
        case 70: break;
        case 46: 
          { return createSymbol(sym.PROGRAM, yytext());
          }
        case 71: break;
        case 19: 
          { return createSymbol(sym.RSQUARE, yytext());
          }
        case 72: break;
        case 14: 
          { return createSymbol(sym.COMMA, yytext());
          }
        case 73: break;
        case 13: 
          { return createSymbol(sym.SEMICOLON, yytext());
          }
        case 74: break;
        case 50: 
          { return createSymbol(sym.IMPLEMENTS, yytext());
          }
        case 75: break;
        case 23: 
          { return createSymbol(sym.INC, yytext());
          }
        case 76: break;
        case 20: 
          { return createSymbol(sym.LCURLY, yytext());
          }
        case 77: break;
        case 35: 
          { return createSymbol(sym.CHAR, yytext());
          }
        case 78: break;
        case 10: 
          { return createSymbol(sym.ASSIGN, yytext());
          }
        case 79: break;
        case 49: 
          { return createSymbol(sym.INTERFACE, yytext());
          }
        case 80: break;
        case 17: 
          { return createSymbol(sym.RPARENT, yytext());
          }
        case 81: break;
        case 47: 
          { return createSymbol(sym.EXTENDS, yytext());
          }
        case 82: break;
        case 31: 
          { return createSymbol(sym.OR, yytext());
          }
        case 83: break;
        case 43: 
          { return createSymbol(sym.CONST, yytext());
          }
        case 84: break;
        case 3: 
          { return createSymbol(sym.IDENT, yytext());
          }
        case 85: break;
        case 1: 
          { System.err.println("[Lexer] Error:  Token \"" + yytext() + "\" could not be identified (Line: " + (yyline + 1) + ", Column: " + yycolumn + ")");
          }
        case 86: break;
        case 25: 
          { yybegin(YYCOMMENT);
          }
        case 87: break;
        case 27: 
          { return createSymbol(sym.NEQ, yytext());
          }
        case 88: break;
        case 42: 
          { return createSymbol(sym.BREAK, yytext());
          }
        case 89: break;
        case 26: 
          { return createSymbol(sym.EQU, yytext());
          }
        case 90: break;
        case 22: 
          { return createSymbol(sym.IF, yytext());
          }
        case 91: break;
        case 39: 
          { return createSymbol(sym.BOOL, yytext());
          }
        case 92: break;
        case 24: 
          { return createSymbol(sym.DEC, yytext());
          }
        case 93: break;
        case 12: 
          { return createSymbol(sym.LST, yytext());
          }
        case 94: break;
        case 34: 
          { return createSymbol(sym.FOR, yytext());
          }
        case 95: break;
        case 18: 
          { return createSymbol(sym.LSQUARE, yytext());
          }
        case 96: break;
        case 37: 
          { return createSymbol(sym.ELSE, yytext());
          }
        case 97: break;
        case 48: 
          { return createSymbol(sym.CONTINUE, yytext());
          }
        case 98: break;
        case 15: 
          { return createSymbol(sym.PERIOD, yytext());
          }
        case 99: break;
        case 2: 
          { 
          }
        case 100: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            { return createSymbol(sym.EOF);
        	}
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }
}